services:
  RL-Coordinator:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - FTP_PROXY=$FTP_PROXY
        - ftp_proxy=$ftp_proxy
        - NO_PROXY=$NO_PROXY
        - no_proxy=$no_proxy
    runtime: nvidia
    image: nvidia/cuda:11.3.1-devel-ubuntu20.04
    container_name: ${USER}.RL-Coordinator
    volumes:
      - ${PWD}:/workspace 
    ports:
      - 8888
      - 6666
    command: bash
    tty: true
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - http_proxy=$http_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
      - https_proxy=$https_proxy
      - FTP_PROXY=$FTP_PROXY
      - ftp_proxy=$ftp_proxy
      - NO_PROXY=$NO_PROXY
      - no_proxy=$no_proxy
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: [utility, compute, video]
