# four pillar, random start, random goal, random obstacles from candidates
# obstacle motion is static with random motion and place
name: "four_pillar_random_static"
known_static_map: "maps/four_pillar"
random_map_mode: True
min_path_length_ratio: 0.9 # [-] minimum path length ratio to the map size
# unknown_static_obs: "maps/star.yaml"
# NOTE: known_static_map and unknown_static_obs must be the same size and resolution
start_pose_type: "candidates" # "candidates" or "specified" or "random"
start_pose:
  x: 2.0
  y: 2.0
  yaw: -0.75
goal_pose_type: "candidates" # "candidates" or "specified" or "random"
goal_pose:
  x: 22
  y: 22
  yaw: 0.0

start_pose_candidates:
  - id: 0
    x: 2.0
    y: 2.0
    yaw: -0.75
  - id: 1
    x: 2.0
    y: 22.0
    yaw: -0.75
  - id: 2
    x: 22.0
    y: 2.0
    yaw: 2.25
  - id: 3
    x: 22.0
    y: 22.0
    yaw: 2.25

goal_pose_candidates:
  - id: 0
    x: 2.0
    y: 2.0
    yaw: -0.75
  - id: 1
    x: 2.0
    y: 22.0
    yaw: -0.75
  - id: 2
    x: 22.0
    y: 2.0
    yaw: 2.25
  - id: 3
    x: 22.0
    y: 22.0
    yaw: 2.25

start_pose_constraints:
  x:
    max: 22
    min: 2
  y:
    max: 22
    min: 2
  yaw:
    max: 3.14
    min: -3.14

goal_pose_constraints:
  x:
    max: 22
    min: 3
  y:
    max: 22
    min: 3
  yaw:
    max: 3.14
    min: -3.14

moving_obstacles:
  type: "random" # "candidates" or "all" or "random"
  num: 8
  candidates:
    - id: 0
      shape: "circle"
      size: [1.5, 0]
      motion_model: ["point_mass_model"]
      x: 7.5
      y: 2.5
      yaw: 0.0
      vx: 0.0
      vy: 0.0
      vyaw: 0.0

  constraints:
    size:
      max: [1.5, 0.0]
      min: [1.5, 0.0]
    position:
      x:
        max: 22
        min: 3
      y:
        max: 22
        min: 3
      yaw:
        max: 3.14
        min: -3.14
    velocity:
      vx:
        max: 0.0
        min: 0.0
      vy:
        max: 0.0
        min: 0.0
      vyaw:
        max: 0.0
        min: 0.0
