# common map parameters
# map size = [width, height] x resolution [m]
height: 200
width: 200
resolution: 0.25

# indoor and outdoor map number rate
outdoor_map_rate: 1.0

# indoor map parameters
corridor_radius: 5 # corridor diameter = 1+2*corridor_radius
iterations: 50 # number of nodes for the indoor map algorithm
room_number: 10
room_width: 60
room_height: 50
no_overlap: True # whether or not rooms are allowed to overlap

# outdoor map parameters
obstacle_number: 20 # number of outdoor obstacles
obstacle_extra_radius: 5 # obstacle diameter = 1+2*obstacle_extra_radius

# define maptype to be generated
maptype: "outdoor" # "indoor" or "outdoor"
map_name: ""
save_dir: "maps"
