# common map parameters
# map size = [width, height] x resolution [m]
common:
  height: 100
  width: 100
  resolution: 0.25
  maptype: "indoor" # "indoor" or "outdoor"
  map_name: "indoor_small"
  save_dir: "maps/eval"

# indoor map parameters
indoor:
  corridor_radius: 4 # corridor diameter = 1+2*corridor_radius
  iterations: 50 # number of nodes for the indoor map algorithm
  room_number: 3
  room_width: 30
  room_height: 30
  no_overlap: True # whether or not rooms are allowed to overlap

