# common map parameters
# map size = [width, height] x resolution [m]
common:
  height: 250
  width: 250
  resolution: 0.1
  maptype: "uniform" # "indoor" or "outdoor" or "simplest" or "uniform"
  map_name: "nine_pillar"
  save_dir: "maps/nine_pillar"

# simplest map parameters
uniform:
  obstacle_num: [3, 3]
  obstacle_size: 15
