# common map parameters
# map size = [width, height] x resolution [m]
common:
  height: 100
  width: 100
  resolution: 0.25
  maptype: "outdoor" # "indoor" or "outdoor"
  map_name: "outdoor_small"
  save_dir: "maps/eval"

# outdoor map parameters
outdoor:
  obstacle_number: 20 # number of outdoor obstacles
  obstacle_extra_radius: 3 # obstacle diameter = 1+2*obstacle_extra_radius

