# common map parameters
# map size = [width, height] x resolution [m]
common:
  height: 100
  width: 100
  resolution: 0.25
  maptype: "simplest" # "indoor" or "outdoor" or "simplest"
  map_name: "simplest"
  save_dir: "maps/simplest"

# simplest map parameters
simplest:
  obstacle_positions: [[50, 50]]
  obstacle_sizes: [[20, 20]]
