# common map parameters
# map size = [width, height] x resolution [m]
common:
  height: 250
  width: 250
  resolution: 0.1
  maptype: "uniform" # "indoor" or "outdoor" or "simplest" or "uniform"
  map_name: "thirty_two_pillar"
  save_dir: "maps/thirty_two_pillar"

# simplest map parameters
uniform:
  obstacle_num: [8, 4]
  obstacle_size: 3
