# common map parameters
# map size = [width, height] x resolution [m]
common:
  height: 250
  width: 250
  resolution: 0.1
  maptype: "uniform" # "indoor" or "outdoor" or "simplest" or "uniform"
  map_name: "twenty_five_pillar"
  save_dir: "maps/twenty_five_pillar"

# simplest map parameters
uniform:
  obstacle_num: [5, 5]
  obstacle_size: 5
