# parameters for navigation

name: "square"
known_static_map: "maps/square/map.yaml"
unknown_static_obs: "maps/star/map.yaml"
random_map_mode: False
min_path_length_ratio: 0.5 # [-] minimum path length ratio to the map size
# NOTE: known_static_map and unknown_static_obs must be the same size and resolution
start_pose_type: "specified" # "candidates" or "specified"
start_pose:
  x: 0.0
  y: 0.0
  yaw: 0.0
goal_pose_type: "specified" # "candidates" or "specified" or "random"
goal_pose:
  x: 10.0
  y: -10.0
  yaw: 0.0

start_pose_candidates:

goal_pose_candidates:

start_pose_constraints:

goal_pose_constraints:

moving_obstacles:
  type: "candidates" # "candidates" or "all"
  num: 0
  candidates:
    - id: 0
      shape: "circle"
      size: [1.0, 0]
      motion_model: "point_mass_model"
      x: 0.0
      y: -7.0
      yaw: 0.0
      vx: 1.0
      vy: 0.0
      vyaw: 1.0
    - id: 1
      shape: "circle"
      size: [1.0, 0]
      motion_model: "point_mass_model"
      x: 7.0
      y: 0.0
      yaw: 0.0
      vx: 1.0
      vy: 0.0
      vyaw: 1.0
